### ISSUE TITLE
Begins downloading, then fails with the following error message

### ISSUE THREAD

**Issue by githubber** [TheFox/flickr-cli#48]
```
[Guzzle\Http\Exception\ServerErrorResponseException]
  Server error response
  [status code] 500
  [reason phrase] Internal Server Error
  [url] https://api.flickr.com/services/rest/
```
I'm trying to download my entire Flickr account with `./bin/flickr-cli download -c data/config.yml -d /home/user/flickr --id-dirs`, but it gets about 13MB in and fails with that message. It is installed in /opt/, so I'm wondering if permissions are an issue?

A related error (I think) was:
```
[file] 1,281,658
PHP Fatal error:  Uncaught Error: Call to undefined function Rych\ByteSize\Formatter\bccomp() in /opt/flickr/flickr-cli/vendor/rych/bytesize/src/Formatter/AbstractFormatter.php:152
Stack trace:
#0 /opt/flickr/flickr-cli/vendor/rych/bytesize/src/Formatter/AbstractFormatter.php(55): Rych\ByteSize\Formatter\AbstractFormatter->normalizeBytes()
#1 /opt/flickr/flickr-cli/vendor/rych/bytesize/src/ByteSize.php(56): Rych\ByteSize\Formatter\AbstractFormatter->format()
#2 /opt/flickr/flickr-cli/src/TheFox/FlickrCli/Command/DownloadCommand.php(473): Rych\ByteSize\ByteSize->format()
#3 /opt/flickr/flickr-cli/src/TheFox/FlickrCli/Command/DownloadCommand.php(597): TheFox\FlickrCli\Command\DownloadCommand->downloadPhoto()
#4 /opt/flickr/flickr-cli/src/TheFox/FlickrCli/Command/DownloadCommand.php(534): TheFox\FlickrCli\Command\DownloadCommand->downloadPhotoById()
#5 /opt/flickr/flickr-cli/src/TheFox/FlickrCli/Command/DownloadCommand.php(113): TheFox\FlickrCli\Command\DownloadCommand->downloadById()
#6 /opt/flickr/flickr-cli/vendor/symfony/cons in /opt/flickr/flickr-cli/vendor/rych/bytesize/src/Formatter/AbstractFormatter.php on line 152
```
This happened at the 13MB point, and now it won't start.
My VPS has 2GB ram... would this be a problem trying to download so much?
Plus, thank you for making something like this!

**Comment by githubber** [comment]
I found an earlier message during installation:
```
Problem 1
    - Installation request for rych/bytesize v1.0.0 -> satisfiable by rych/bytesize[v1.0.0].
    - rych/bytesize v1.0.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
```
This is probably why the error is happening. I'll try to fix that.

**Comment by githubber** [comment]
Yeah, that seems to have done the trick. I hope you see this before spending any time on answering. Feel free to remove it if you wish, but I'll leave it up just in case someone else like me makes a similar mistake. I assumed that because it installed it would work. I should pay attention to the warnings! Thanks again, and happy new year!
